name: Test

on:
  push:
    branches:
      - master
      - derby-2
  pull_request:
    branches:
      - master
      - derby-2

jobs:
  test:
    name: Node ${{ matrix.node }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node:
          - 12
          - 14
          - 16
          - 18
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Install
        run: npm install
      - name: Test
        run: npm run test
